apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: jib-maven
spec:
  parameters:
  - name: IMAGE
    description: The name of the image to push
  - name: DIRECTORY
    description: The directory containing the app, relative to the source repository root
    default: .
  - name: CACHE
    description: The name of the volume for caching Maven artifacts and base image layers
    default: empty-dir-volume

  steps:
  - name: docker-creds-helper
    image: golang:1.11.4
    command: ["/bin/bash"]
    args:
    - -c
    - |
      go get github.com/GoogleCloudPlatform/docker-credential-gcr;
      cp /go/bin/docker-credential-gcr /usr/local/bin;
    volumeMounts:
    - name: ${CACHE}
      mountPath: /usr/local/bin
  - name: build-and-push
    image: gcr.io/cloud-builders/mvn
    args:
    - compile
    - com.google.cloud.tools:jib-maven-plugin:build
    - -Duser.home=/builder/home
    - -Dimage=${IMAGE}
    workingDir: /workspace/${DIRECTORY}
    volumeMounts:
    - name: ${CACHE}
      mountPath: /usr/local/bin
    - name: ${CACHE}
      mountPath: /builder/home/.m2
      subPath: m2-cache
    - name: ${CACHE}
      mountPath: /builder/home/.cache
      subPath: jib-cache

  volumes:
  - name: empty-dir-volume
    emptyDir: {}
