---
apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: buildpackv3
spec:
  parameters:
  - name: IMAGE
    description: The image you wish to create. For example, "repo/example", or "example.com/repo/image".
  - name: RUN_IMAGE # TODO: add more options when Build permits
    description: The run image buildpacks will use as the base for IMAGE.
    default: packs/v3:run
  - name: USE_CREDENTIAL_HELPERS
    description: Use Docker credential helpers for Google's GCR, Amazon's ECR or Microsoft's ACR.
    default: 'true'

  steps:
  - name: chown-home-workspace
    image: packs/v3:latest
    command: ["chown", "-R", "packs", "/builder/home", "/workspace"]
  - name: copy-app
    image: packs/v3:detect
    command: ["cp", "-R", "/workspace", "/launch/app"]
    volumeMounts:
    - name: launch
      mountPath: /launch
    imagePullPolicy: Always
  - name: detect
    image: packs/v3:detect
    workingDir: /lifecycleworkspace # Build creates a /workspace, which buildpacks tries to use for a different purpose.
    volumeMounts:
    - name: lifecycleworkspace
      mountPath: /lifecycleworkspace
    - name: launch
      mountPath: /launch
    imagePullPolicy: Always
  - name: analyze
    image: packs/v3:analyze
    args: ["${IMAGE}"]
    env:
    - name: PACK_USE_HELPERS
      value: ${USE_CREDENTIAL_HELPERS}
    workingDir: /lifecycleworkspace
    volumeMounts:
    - name: lifecycleworkspace
      mountPath: /lifecycleworkspace
    - name: launch
      mountPath: /launch
    imagePullPolicy: Always
  - name: build
    image: packs/v3:build
    workingDir: /lifecycleworkspace
    volumeMounts:
    - name: lifecycleworkspace
      mountPath: /lifecycleworkspace
    - name: launch
      mountPath: /launch
    - name: cache
      mountPath: /cache
    imagePullPolicy: Always
  - name: export
    image: packs/v3:export
    args: ["${IMAGE}"]
    env:
    - name: PACK_RUN_IMAGE
      value: ${RUN_IMAGE}
    - name: PACK_USE_HELPERS
      value: ${USE_CREDENTIAL_HELPERS}
    workingDir: /lifecycleworkspace
    volumeMounts:
    - name: lifecycleworkspace
      mountPath: /lifecycleworkspace
    - name: launch
      mountPath: /launch
    imagePullPolicy: Always

  volumes:
  - name: launch
    emptyDir: {}
  - name: lifecycleworkspace
    emptyDir: {}
  - name: cache
    emptyDir: {}
