---
apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: buildpacks-cnb
spec:
  parameters:
  - name: IMAGE
    description: The image you wish to create. For example, "repo/example", or "example.com/repo/image".
  - name: RUN_IMAGE
    description: The run image buildpacks will use as the base for IMAGE.
    default: packs/run
  - name: USE_CRED_HELPERS
    description: Use Docker credential helpers for Google's GCR, Amazon's ECR, or Microsoft's ACR.
    default: 'true'
  - name: CACHE
    description: The name of the persistent app cache volume
    default: app-cache

  steps:
  - name: prepare
    image: packs/base
    command: ["/lifecycle/knative-helper"]
    volumeMounts:
    - name: "${CACHE}"
      mountPath: /cache
    imagePullPolicy: Always
  - name: detect
    image: packs/samples
    command: ["/lifecycle/detector"]
    imagePullPolicy: Always
  - name: analyze
    image: packs/util
    command: ["/lifecycle/analyzer"]
    args: ["${IMAGE}"]
    env:
    - name: PACK_USE_HELPERS
      value: ${USE_CRED_HELPERS}
    imagePullPolicy: Always
  - name: build
    image: packs/samples
    command: ["/lifecycle/builder"]
    volumeMounts:
    - name: "${CACHE}"
      mountPath: /cache
    imagePullPolicy: Always
  - name: export
    image: packs/util
    command: ["/lifecycle/exporter"]
    args: ["${IMAGE}"]
    env:
    - name: PACK_RUN_IMAGE
      value: ${RUN_IMAGE}
    - name: PACK_USE_HELPERS
      value: ${USE_CRED_HELPERS}
    imagePullPolicy: Always

  volumes:
  - name: app-cache
    emptyDir: {}
