apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: makisu
spec:
  parameters:
  - name: IMAGE
    description: The name of the image to push
  - name: CONTEXTPATH
    description: Path to the build context.
    default: /workspace
  - name: PUSH_REGISTRY
    description: Registry to push image to.
    default: index.docker.io
  - name: REGISTRY_SECRET
    description: Secret containing information about the used registry.
    default: docker-registry-config
  steps:
  - name: build-and-push
    image: gcr.io/makisu-project/makisu:v0.1.9
    args:
      - build
      - --push=${PUSH_REGISTRY}
      - --registry-config=/registry-config
      - --modifyfs=true
      - --tag=${IMAGE}
      - --registry-config=/registry-config/registry.yaml
      - ${CONTEXTPATH}
    env:
    - name: DOCKER_CONFIG
      value: /builder/home/.docker
    volumeMounts:
    - name: registry-config
      mountPath: /registry-config
  volumes:
  - name: registry-config
    secret:
      secretName: ${REGISTRY_SECRET}
